# Generated by Django 3.0.3 on 2020-06-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(blank=True, max_length=110)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='代码')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=110)),
                ('cron', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.CrontabSchedule')),
            ],
            options={
                'verbose_name': 'cron单位',
                'verbose_name_plural': 'cron单位',
            },
        ),
    ]
