# Generated by Django 3.0.3 on 2020-06-15 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名字')),
                ('args', models.CharField(blank=True, max_length=20, verbose_name='参数')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('is_one', models.BooleanField(default=False, verbose_name='仅执行一次')),
                ('cron', models.CharField(blank=True, max_length=20, verbose_name='cron表达式')),
                ('code_type', models.CharField(choices=[('shell', 'shell'), ('python', 'python')], default='shell', max_length=10, verbose_name='code类型')),
                ('code', models.TextField(blank=True, verbose_name='脚本代码')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='开始时间')),
                ('expire_time', models.DateTimeField(blank=True, verbose_name='到期时间')),
                ('action_time', models.DateTimeField(blank=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '任务脚本',
                'verbose_name_plural': '任务脚本',
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('args', models.CharField(blank=True, max_length=20, verbose_name='参数')),
                ('status', models.CharField(choices=[('running', 'running'), ('success', 'success'), ('fail', 'fail')], default='running', max_length=10, verbose_name='状态')),
                ('log', models.TextField(blank=True, verbose_name='日志')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='结束时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celery_tasks.Task')),
            ],
            options={
                'verbose_name': '任务脚本',
                'verbose_name_plural': '任务脚本',
            },
        ),
    ]
