# Generated by Django 3.0.3 on 2020-06-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='action_time',
        ),
    ]
